---
title: "STOR556 Project Main"
output: html_notebook
---

```{r}
#import necessary packages
library(readr)
library(itsmr)
library(gplots)
#import R scripts
source("~/Documents/differencing.R")
source("~/Documents/stationarizing.R")
#import data from local file
co2_data <- read_table2("~/Downloads/co2_data.txt")
x <- c(co2_data$interpolated)
#plots of the initial time series
plot(x, type="l", xlab="t", ylab=expression("X"["t"]*" (ppm)"), main=expression("Carbon Dioxide Time Series X"["t"]))
plota(x)
```

```{r}
#stationarize by deseasonlizing and subtracting fitted quadratic polynomial
r = stationarizing(x, 12, 2)
#use autofit function to fit an arma to the stationary residuals
r.arma = autofit(r, 0:5, 0:5)
e = Resid(r, NULL, r.arma)
#plot and test the new residuals
plot(e, 
     type="l", 
     xlab="t", 
     ylab=expression("e"["t"]), 
     main=expression("Plot of e"["t"]))
plota(e)
test(e)
```

```{r}
co2_gr <- read_table2("~/Downloads/co2_gr_mlo.txt")
plot(ann_inc~year, data=co2_gr, type="l", ylab="Annual increase (ppm)", xlab="Year", main=expression("Plot of annual CO"["2"]*" increase"))
gr = co2_gr$ann_inc
plot(smooth.ma(gr, 10)~co2_gr$year, type="l", ylab="Annual increase (ppm)", xlab="Year", main=expression("Plot of annual CO"["2"]*" increase after applying MA(10) filter"))

d=x-season(x,12)
t=c(1:740)
trend.q = lm(d~I(t^2)+t)
summary=summary(trend.q)
plot(d~t, type="l",  main="Plot of fitted quadratic curve", ylab=expression("d"["t"]*" (ppm)"), xlab="t")
curve(summary$coefficients[2,1]*(x^2) + summary$coefficients[3,1]*x
      + summary$coefficients[1,1], add=TRUE, col="red")
```
```{r}
plota(d)
```

```{r}
#95% and 99% CI for November 2019 prediction
a=forecast(x, c("season", 12, "trend", 2), r.arma, h=1, opt=1, alpha=.05)
b=forecast(x, c("season", 12, "trend", 2), r.arma, h=1, opt=1, alpha=.01)
```

```{r}
#Create estimation dataset x.1
x.p = c(x[c(1:length(x))], a$pred[1])
#xhat is the t value (index in Xt) of November 2019
xhat = length(x.p)

#plotting 95% and 99% confidence intervals
plot(c(720:xhat), x.p[c(720:xhat)], type="l", ylim=c(406, 415), main="95% CI for November 2019 Prediction", ylab=expression("X"["t"]*" (ppm)"), xlab="t")
plotCI(xhat, a$pred[1], ui=a$u[1], li=a$l[1], gap=0, col="red", add=TRUE)

plot(c(720:xhat), x.p[c(720:xhat)], type="l", ylim=c(406, 415), main="99% CI for November 2019 Prediction", ylab=expression("X"["t"]*" (ppm)"), xlab="t")
plotCI(xhat, b$pred[1], ui=b$u[1], li=b$l[1], col="blue", gap = 0, add=TRUE)

plot(c(720:xhat), x.p[c(720:xhat)], type="l", ylim=c(406, 415), main="95% and 99% CI for November 2019 Prediction", ylab=expression("X"["t"]*" (ppm)"), xlab="t")
plotCI(xhat, a$pred[1], ui=a$u[1], li=a$l[1], gap=0, col="red", add=TRUE)
plotCI(xhat, b$pred[1], ui=b$u[1], li=b$l[1], gap=0, col="blue", add=TRUE)
```
